### ISSUE TITLE
Only detect indentation at the beginning of lines

### ISSUE THREAD

**Issue by trypsynth** [pitermach/IndentBeeper#1]
Currently, this spoon beeps if you have two spaces or a tab anywhere in the text under the cursor. This is annoying at times, and makes reading older documents (such as the GPL with two spaces after periods), especially annoying and beepy. It would be great if this could be made more like NVDA, so it only beeps if the line starts with indentation

**Comment by pitermach** [comment]
Good catch. It should be smarter about this now.

**Comment by trypsynth** [comment]
Awesome! Thanks! I love this thing.
