### ISSUE TITLE
Spoon stops working after auto-sleep

### ISSUE THREAD

**Issue by trypsynth** [pitermach/IndentBeeper#2]
I have my Mac set to auto-sleep after 5 minutes. However, after it does this and I wake it up, IndentBeeper stops beeping until I reload the config from the Hammerspoon menu.

This probably has something to do with the method of sound playback being used. For what it's worth, whatever Arfy's SoundNote replacement does doesn't break when the machine goes to sleep.

**Comment by pitermach** [comment]
I can't reproduce this by putting the system to sleep, but I have seen a few freezes that may be more related to trying to read the text from the focused controls.

When this next happens, open the hammerspoon console and send me any error lines you might see at the bottom, that'll help tracking it down.

**Comment by ogomez92** [comment]
This issue seems to stil be realted to AXRangeForline paramter (line
39). I have forked the repo in case I find a solution and if so, will
create a pr. The bad thing is that I can't seem to reproduce the issue
on purpose, it seems to happen on certain random controls. I'll try to
pay more attention to this next time it happens.

**Comment by trypsynth** [comment]
Yeah, I wasn't entirely sure if putting it to sleep did it, but that seemed the most reliable trigger. Probably just a fluke though. I'll investigate.

**Comment by trypsynth** [comment]
@Pitermach, here's the error I get. 2022-01-24 21:18:23: 21:18:23 ERROR:   LuaSkin: hs.timer callback error: /Users/quin/.hammerspoon/Spoons/IndentBeeper.spoon/init.lua:40: method 'AXStringForRangeWithParameter' is not callable (a nil value)
stack traceback:
	/Users/quin/.hammerspoon/Spoons/IndentBeeper.spoon/init.lua:40: in function 'getCurrentLine'
	/Users/quin/.hammerspoon/Spoons/IndentBeeper.spoon/init.lua:84: in function 'checkIndent'

**Comment by ogomez92** [comment]
Yep I get the same error sometimes but I can’t seem to find a reliable way to reproduce it.

**Comment by pitermach** [comment]
Hmmm.

It looks like above this I'm checking if this function isn't nil which is what I thought this error means. unless it's complaining about the line number that's being passed. I can check for that too but because we don't have 100% reproducible steps it might be a while before we figure out if that's what it is.

**Comment by pitermach** [comment]
Try this latest version for a while and if this still comes up reopen this issue.

**Comment by pitermach** [comment]
Nope, it's still happening. I think it may be related to the login window in some way judging by the logging messages I got from triggrd, but I'm not sure how to fix it.

**Comment by trypsynth** [comment]
@pitermach, just sat down with this, and try changing line 38 to:
```lua
if element.AXRangeForLineWithParameter ~= nil and element.AXStringForRangeWithParameter ~= nil and lineNum ~= nil then
```
The notable change is also checking for AXStringForRangeWithParameter not being nil, as I get 'AXStringForRangeWithParameter' is not callable (a nil value)
About to PR this, but want to have others test to make sure it didn't just fix it on my Mac.

**Comment by ogomez92** [comment]
You should PR and then we will test, it's probably easier than each of
us making the code change. *smile*

**Comment by trypsynth** [comment]
See #3

**Comment by pitermach** [comment]
Thanks for hopefully figuring this out!
